spring:
   profiles:
      active: development
   application:
      name: PKSUpgradeTester
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  metrics:
    export:
      atlas:
        enabled: false
server:
  port: ${TOMCAT_PORT}