spring:
   profiles:
      active: development
   application:
      name: PKSUpgradeTester
management:
   endpoints:
      web:
         exposure:
            include: "*"
server:
  port: ${TOMCAT_PORT}